{{- $releaseName := .Release.Name -}}
{{- $chartName := include "mapproxy-mapnik.name" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $releaseName }}-{{ $chartName }}-secret
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "mapproxy-mapnik.environment" . }}
    release: {{ $releaseName }}
    {{- include "mapproxy-mapnik.labels" . | nindent 4 }}
type: Opaque
data:
  PGUSER: {{ .Values.dbConfig.username | b64enc }}
  PGPASSWORD: {{ .Values.dbConfig.password | b64enc }}
{{- end }}